### ISSUE TITLE
Disagrees with twox_hash about hash values?

### ISSUE THREAD

**Issue by sourcefrog** [cberner/xxh3#9]
It seems like xxh3 and twox_hash return different values from the same input? I have not yet checked against the C reference implementation.

A fragment of code

```rust
            let mut hasher = XxHash64::with_seed(0);
            hasher.write(&buf);
            let calc_twox_hash = hasher.finish().to_be_bytes();
            dbg!(&calc_twox_hash);

            let xxh3_value = xxh3::hash64_with_seed(&buf, 0);
            dbg!(&xxh3_value.to_be_bytes());
```

```
&calc_twox_hash = [
    8,
    182,
    105,
    74,
    21,
    17,
    27,
    162,
]
&xxh3_value.to_be_bytes() = [
    162,
    69,
    50,
    180,
    67,
    164,
    229,
    136,
]
```

(This is on an M1 mac.)

**Comment by cberner** [comment]
Can you check it against the reference implementation? I have this fuzzer which does that, and I expect would have caught an issue: https://github.com/cberner/xxh3/blob/master/fuzz/fuzz_targets/fuzz_xxh3.rs

**Comment by sourcefrog** [comment]
Yes, your xxh3 crate matches the reference implementation and `twox_hash` does not.

I guess https://github.com/shepmaster/twox-hash/pull/52 might fix it on that side.

Sorry for the noise!
